using Luthor;

using System.Reflection;
using System.Text;
using System.Xml.Linq;
namespace LexGen
{
    record Rule(string Name, string Pattern, bool IsHidden = false);

    internal class Program
    {
        const string _KeywordMap = "|abstract|add|as|ascending|async|await|base|bool|break|byte|case|catch|char|checked|class|const|continue|decimal|default|delegate|descending|do|double|dynamic|else|enum|equals|explicit|extern|false|finally|fixed|float|for|foreach|get|global|goto|if|implicit|int|interface|internal|is|lock|long|namespace|new|null|object|operator|out|override|params|partial|private|protected|public|readonly|record|ref|remove|return|sbyte|sealed|set|short|sizeof|stackalloc|static|string|struct|switch|this|throw|true|try|typeof|uint|ulong|unchecked|unsafe|ushort|using|var|virtual|void|volatile|while|yield|";
        static void DumpArray(int[] array, int indent, TextWriter writer)
        {
            var spaces = new string(' ', indent);
            writer.Write(spaces);
            for (var i = 0; i < array.Length; i++)
            {
                if (i > 0 && (i % 16 == 0))
                {
                    writer.WriteLine();
                    writer.Write(spaces);
                }
                writer.Write(array[i]);
                if (i < array.Length - 1)
                {
                    writer.Write(", ");
                }
            }
        }
        static List<Rule> ReadRules(TextReader reader)
        {
            var list = new List<Rule>();
            var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            string? line;
            while(null!=(line=reader.ReadLine())) {
                var i = line.IndexOf("//");
                if(i >= 0)
                    line = line.Substring(0, i);
                line = line.Trim();
                if(line.Length == 0)
                    continue;
                var hidden = false;
                if (line[0]=='.')
                {
                    hidden = true;
                    line = line.Substring(1);
                }
                i = line.IndexOf(' ');

                if (i < 0) 
                { 
                    if(hidden) line = "."  + line;
                    throw new Exception($"Invalid rule: {line}"); 
                }
                var name = line.Substring(0, i);
                var pattern = line.Substring(i + 1).TrimStart();
                list.Add(new Rule(name, pattern, hidden));
            }
            return list;
        }
        static void Main(string[] args)
        {
            Options? toDispose = null;
            try
            {
                Console.OutputEncoding = Encoding.UTF8;

                if (!Options.TryCreate(args, out var options, out var error))
                {
                    if (!error!.IsHelpRequest)
                    {
                        Console.Error.WriteLine("Error: " + error.Message);
                        Console.Error.WriteLine();
                    }
                    Options.PrintUsage();
                    return;
                }
                toDispose = options;
                var rules = ReadRules(options.Input);
                var cpDfa = Builder.Build(rules.Select(p=>p.Pattern).ToList(), true,options.Unicode);
                var array = Compiler.Compile(cpDfa, "UTF-16");
                var writer = options.Output;
                writer.WriteLine("// <auto-generated />");
                writer.WriteLine();
                if(options.Namespace!=null)
                {
                    writer.WriteLine($"namespace {options.Namespace};");
                    writer.WriteLine();
                }
                using var resReader = new StreamReader(Assembly.GetEntryAssembly()!.GetManifestResourceStream("LexGen.Templates.LuthorRuntime.cs")!);
                
                string? line;
                while (null != (line = resReader.ReadLine()))
                {
                    writer.WriteLine(line);
                }
                //(long Position, int Symbol, string Text)
                var className = options.Class ?? CliUtility.GetFilename(options.Input)??"Lexer";
                if(options.Public)
                {
                    writer.Write("public ");
                }
                writer.WriteLine($"static class {className}");
                writer.WriteLine("{");
                writer.WriteLine("    private static int[] _dfa = {");
                DumpArray(array, 8, writer);
                writer.WriteLine();
                writer.WriteLine("    };");
                writer.WriteLine("    public static IEnumerable<Parsley.Runtime.Token> Tokenize(TextReader reader, long position = 0, int line = 1, int column = 1, int tabWidth = 4) {");
                writer.WriteLine("        foreach(var tok in LuthorRuntime.Tokenize(_dfa, reader, tabWidth, position, line, column))");
                writer.WriteLine("        {");
                var hiddenRules = rules.Where(p => p.IsHidden).Select(p => p.Name).ToList();
                if (hiddenRules.Count > 0)
                {
                    writer.Write("            if(");
                    for (var j = 0; j < hiddenRules.Count; j++)
                    {
                        var hidden = hiddenRules[j];
                        if (j > 0)
                            writer.Write(" || ");
                        writer.Write($"tok.Symbol == {hidden}");
                    }
                    writer.WriteLine(") continue;");
                }
                writer.WriteLine("            yield return new Parsley.Runtime.Token(tok.Symbol, tok.Text, tok.Line, tok.Column, tok.Position);");
                writer.WriteLine("        }");
                writer.WriteLine("    }");
                writer.WriteLine("    public static IEnumerable<Parsley.Runtime.Token> Tokenize(string text, long position = 0, int line = 1, int column = 1, int tabWidth = 4) {");
                writer.WriteLine("        foreach(var tok in LuthorRuntime.Tokenize(_dfa, text, tabWidth, position, line, column))");
                writer.WriteLine("        {");
                hiddenRules = rules.Where(p => p.IsHidden).Select(p => p.Name).ToList();
                if (hiddenRules.Count > 0)
                {
                    writer.Write("            if(");
                    for (var j = 0; j < hiddenRules.Count; j++)
                    {
                        var n = hiddenRules[j];
                        if (_KeywordMap.Contains($"|{n}|")) n = "@" + n;

                        if (j > 0)
                            writer.Write(" || ");
                        writer.Write($"tok.Symbol == {n}");
                    }
                    writer.WriteLine(") continue;");
                }
                writer.WriteLine("            yield return new Parsley.Runtime.Token(tok.Symbol, tok.Text, tok.Line, tok.Column, tok.Position);");
                writer.WriteLine("        }");
                writer.WriteLine("    }");
                var i = 0;
                foreach (var name in rules.Select(p=>p.Name))
                {
                    var n = name;
                    if(_KeywordMap.Contains($"|{name}|")) n = "@" + name;
                    writer.WriteLine($"    public const int {n} = {i};");
                    i++;
                }
                writer.WriteLine($"    public const int ERROR = {i};");
                writer.WriteLine("}");
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Error: {ex.Message}");
            }
            finally
            {
                toDispose?.Dispose();
            }
        }
    }
}
