// <auto-generated>
// Synthesized by Parsley from json.xbnf. Changes are lost when it is synthesized again;
// add members in another part of this partial class instead.
// </auto-generated>
#nullable enable
using System.Collections.Generic;
using Parsley.Runtime;

/// <summary>
/// Parses Json. Synthesized from json.xbnf.
/// </summary>
public partial class JsonParser : ParserBase
{
	#region Symbols
	public const int Json = 0;
	public const int Object = 1;
	public const int Field = 2;
	public const int Array = 3;
	public const int Value = 4;
	public const int Boolean = 5;
	public const int Number = 6;
	public const int String = 7;
	public const int True = 8; // "true"
	public const int False = 9; // "false"
	public const int Null = 10; // "null"
	public const int Lbracket = 11; // "["
	public const int Rbracket = 12; // "]"
	public const int Lbrace = 13; // "{"
	public const int Rbrace = 14; // "}"
	public const int Colon = 15; // ":"
	public const int Comma = 16; // ","
	public const int Whitespace = 17;
	public const int EndOfInput = 18;
	public const int ErrorSymbol = 19;
	public const int SymbolCount = 20;
	#endregion

	public JsonParser(IEnumerable<Token> tokens) : base(tokens, s_tables) { }

	/// <summary>
	/// Parses a complete Json and returns its tree. Problems are reported in <see cref="ParserBase.Errors"/>.
	/// </summary>
	public static bool TryParse(IEnumerable<Token> tokens,out ParseNode result, out IReadOnlyList<ParseError> errors)
	{
		var parser = new JsonParser(tokens);
		result = parser.Run(parser.ParseJson);
		errors = parser.Errors;
		return parser.Errors.Count == 0;
	}
	public static ParseNode Parse(IEnumerable<Token> tokens)
	{
		if(!TryParse(tokens, out var result, out var errors))
		{
			throw new ParseException(errors);
		}
		return result;
	}

	// Json<start>= Object | Array;
	ParseNode ParseJson()
	{
		Enter(Json);
		var node = NewNode(Json);
		if (Current.SymbolId == Lbrace)
		{
			node.Add(ParseObject());
		}
		else
		{
			node.Add(ParseArray());
		}
		Leave();
		return node;
	}

	// Object= "{" [ Field { "," Field } ] "}";
	ParseNode ParseObject()
	{
		Enter(Object);
		var node = NewNode(Object);
		Expect(Lbrace, node);
		// [ Field { "," Field } ]
		if (Current.SymbolId == String)
		{
			node.Add(ParseField());
			// { "," Field }
			while (Current.SymbolId == Comma)
			{
				Consume(node);
				node.Add(ParseField());
			}
		}
		Expect(Rbrace, node);
		Leave();
		return node;
	}

	// Field= string ":" Value;
	ParseNode ParseField()
	{
		Enter(Field);
		var node = NewNode(Field);
		Expect(String, node);
		Expect(Colon, node);
		ParseValue(node);
		Leave();
		return node;
	}

	// Array= "[" [ Value { "," Value } ] "]";
	ParseNode ParseArray()
	{
		Enter(Array);
		var node = NewNode(Array);
		Expect(Lbracket, node);
		// [ Value { "," Value } ]
		if (Current.SymbolId is not (Rbracket or EndOfInput))
		{
			ParseValue(node);
			// { "," Value }
			while (Current.SymbolId == Comma)
			{
				Consume(node);
				ParseValue(node);
			}
		}
		Expect(Rbracket, node);
		Leave();
		return node;
	}

	// Value<collapsed>= string | number | Object | Array | Boolean | null;
	void ParseValue(ParseNode parent)
	{
		Enter(Value);
		switch (Current.SymbolId)
		{
			case String:
			case Number:
			case Null:
				Consume(parent);
				break;
			case Lbrace:
				parent.Add(ParseObject());
				break;
			case Lbracket:
				parent.Add(ParseArray());
				break;
			case True:
			case False:
				parent.Add(ParseBoolean());
				break;
			default:
				Error(parent, null, Number, String, True, False, Null, Lbracket, Lbrace);
				break;
		}
		Leave();
	}

	// Boolean= true | false;
	ParseNode ParseBoolean()
	{
		Enter(Boolean);
		var node = NewNode(Boolean);
		if (Current.SymbolId == True)
		{
			Consume(node);
		}
		else
		{
			Expect(False, node);
		}
		Leave();
		return node;
	}

	#region Tables
	static readonly ParserTables s_tables = new(
		terminalStart: Number, // lexer ids count terminals from 0; the parser adds this
		symbolNames: ["Json", "Object", "Field", "Array", "Value", "Boolean", "number", "string", "true", "false", "null", "lbracket", "rbracket", "lbrace", "rbrace", "colon", "comma", "whitespace", "#EOS", "#ERROR"],
		displayNames: ["Json", "Object", "Field", "Array", "Value", "Boolean", "number", "string", "\"true\"", "\"false\"", "\"null\"", "\"[\"", "\"]\"", "\"{\"", "\"}\"", "\":\"", "\",\"", "whitespace", "end of input", "an unrecognized token"],
		collapsedTerminals: [Lbracket, Rbracket, Lbrace, Rbrace, Colon, Comma],
		// for each non-terminal, where error recovery can stop while parsing it: what can follow it, plus its sync terminals
		recoverySets:
		[
			[EndOfInput], // Json
			[Rbracket, Rbrace, Comma, EndOfInput], // Object
			[Rbrace, Comma], // Field
			[Rbracket, Rbrace, Comma, EndOfInput], // Array
			[Rbracket, Rbrace, Comma], // Value
			[Rbracket, Rbrace, Comma] // Boolean
		],
		syncTerminals: [],
		endOfInput: EndOfInput,
		error: ErrorSymbol);
	#endregion
}
