// <auto-generated />

namespace Json;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Runtime.CompilerServices;
using System.Text;

// A source of code units for the matcher. Implemented by small structs so the JIT
// specializes Match<T> for each input kind (no interface dispatch in the inner loop).
internal interface ILuthorUnitSource
{
    /// <summary>Code unit at offset from the start of the current token, or -1 at end of input.</summary>
    int Peek(int offset);
}

internal static class LuthorRuntime
{
    internal const int DefaultTabWidth = 4;

    // Flat table layout (see Luthor's Compiler.cs):
    //   dfa[0]  newline code unit (for ^ and $), then per state:
    //   accept, bol, eol, n, n x (min, max, target)

    /// <summary>Longest match at the start of <paramref name="text"/>. Returns (symbol or -1, length in units).</summary>
    internal static (int Token, int Length) Match<T>(int[] dfa, ref T text, bool atLineStart) where T : struct, ILuthorUnitSource
    {
        int state = 1, accept = -1, length = 0, i = 0;
        bool bol = atLineStart;
        while (true)
        {
            int c = text.Peek(i);                                                          // -1 at end of input
            if (bol && dfa[state + 1] != -1) state = dfa[state + 1];                       // ^
            if ((c == -1 || c == dfa[0]) && dfa[state + 2] != -1) state = dfa[state + 2]; // $
            if (dfa[state] != -1) { accept = dfa[state]; length = i; }
            if (c == -1) break;
            int next = -1, r = state + 4;                                                  // (min, max, target) triples, sorted
            for (int k = 0; k < dfa[state + 3] && c >= dfa[r]; k++, r += 3)
                if (c <= dfa[r + 1]) { next = dfa[r + 2]; break; }
            if (next == -1) break;
            state = next;
            bol = c == dfa[0];
            i++;
        }
        return (accept, length);
    }

    static void CheckArgs(int tabWidth, long position, int line, int column)
    {
        if (tabWidth < 1) throw new ArgumentOutOfRangeException(nameof(tabWidth), tabWidth, "Tab width must be at least 1.");
        if (position < 0) throw new ArgumentOutOfRangeException(nameof(position), position, "Position must be zero or greater.");
        if (line < 1) throw new ArgumentOutOfRangeException(nameof(line), line, "Line must be at least 1.");
        if (column < 1) throw new ArgumentOutOfRangeException(nameof(column), column, "Column must be at least 1.");
    }

    // ---------------------------------------------------------------- string

    /// <summary>
    /// Tokenizes <paramref name="text"/>. Position is the zero-based code-unit offset of the token start;
    /// Line and Column are one-based and also refer to the token start.
    /// </summary>
    /// <param name="position">Position reported for the first unit of <paramref name="text"/>.</param>
    /// <param name="line">Line reported for the first unit of <paramref name="text"/>.</param>
    /// <param name="column">Column reported for the first unit of <paramref name="text"/>. The input is treated
    /// as starting at the beginning of a line (for ^) only when this is 1.</param>
    internal static IEnumerable<(long Position, int Line, int Column, int Symbol, string Text)> Tokenize(
        int[] dfa, string text, int tabWidth = DefaultTabWidth, long position = 0, int line = 1, int column = 1)
    {
        if (dfa is null) throw new ArgumentNullException(nameof(dfa));
        if (text is null) throw new ArgumentNullException(nameof(text));
        CheckArgs(tabWidth, position, line, column);
        return TokenizeString(dfa, text, tabWidth, position, line, column);
    }

    static IEnumerable<(long Position, int Line, int Column, int Symbol, string Text)> TokenizeString(
        int[] dfa, string text, int tabWidth, long position, int line, int column)
    {
        var lc = new LineColumnTracker(dfa[0], tabWidth, line, column);
        for (int i = 0; i < text.Length;)
        {
            var src = new StringSource(text, i);
            bool atLineStart = i == 0 ? column == 1 : text[i - 1] == dfa[0];
            var (tok, len) = Match(dfa, ref src, atLineStart);
            if (len == 0) { tok = -1; len = 1; }  // nothing matched (or only an empty match): skip one unit
            int tokLine = lc.Line, tokColumn = lc.Column;
            lc.Advance(text, i, len);
            yield return (position + i, tokLine, tokColumn, tok, text.Substring(i, len));
            i += len;
        }
    }

    readonly struct StringSource : ILuthorUnitSource
    {
        readonly string _text; readonly int _pos;
        public StringSource(string text, int pos) { _text = text; _pos = pos; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int Peek(int offset) => _pos + offset < _text.Length ? _text[_pos + offset] : -1;
    }

    // ---------------------------------------------------------------- TextReader

    /// <summary>
    /// Tokenizes the contents of <paramref name="reader"/>. Position is the zero-based code-unit offset of the
    /// token start; Line and Column are one-based and also refer to the token start.
    /// </summary>
    /// <param name="position">Position reported for the first unit read from <paramref name="reader"/>.</param>
    /// <param name="line">Line reported for the first unit read from <paramref name="reader"/>.</param>
    /// <param name="column">Column reported for the first unit read from <paramref name="reader"/>. The input is
    /// treated as starting at the beginning of a line (for ^) only when this is 1.</param>
    internal static IEnumerable<(long Position, int Line, int Column, int Symbol, string Text)> Tokenize(
        int[] dfa, TextReader reader, int tabWidth = DefaultTabWidth, long position = 0, int line = 1, int column = 1)
    {
        if (dfa is null) throw new ArgumentNullException(nameof(dfa));
        if (reader is null) throw new ArgumentNullException(nameof(reader));
        CheckArgs(tabWidth, position, line, column);
        return TokenizeReader(dfa, reader, tabWidth, position, line, column);
    }

    static IEnumerable<(long Position, int Line, int Column, int Symbol, string Text)> TokenizeReader(
        int[] dfa, TextReader reader, int tabWidth, long position, int line, int column)
    {
        var window = new LuthorCharWindow(reader);
        var lc = new LineColumnTracker(dfa[0], tabWidth, line, column);
        long pos = position;
        bool atLineStart = column == 1;
        while (window.Peek(0) != -1)
        {
            var src = new CharWindowSource(window);
            var (tok, len) = Match(dfa, ref src, atLineStart);
            if (len == 0) { tok = -1; len = 1; }
            atLineStart = window.Peek(len - 1) == dfa[0];
            string s = window.Take(len);
            int tokLine = lc.Line, tokColumn = lc.Column;
            lc.Advance(s, 0, s.Length);
            yield return (pos, tokLine, tokColumn, tok, s);
            pos += len;
        }
    }

    readonly struct CharWindowSource : ILuthorUnitSource
    {
        readonly LuthorCharWindow _w;
        public CharWindowSource(LuthorCharWindow w) => _w = w;
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int Peek(int offset) => _w.Peek(offset);
    }
}

// Tracks one-based line and column across consecutive tokens.
//  - The DFA's newline unit (dfa[0]) ends a line, so line counting agrees with ^ and $.
//  - '\t' advances to the next tab stop (with width 4: columns 1..4 -> 5, 5..8 -> 9).
//  - Other control characters (below U+0020) don't advance the column.
//  - Columns count code points: the low half of a surrogate pair doesn't advance the column,
//    even when the pair is split across two tokens.
internal struct LineColumnTracker
{
    readonly int _newline;
    readonly int _tabWidth;
    bool _afterHighSurrogate;

    public int Line { get; private set; }
    public int Column { get; private set; }

    public LineColumnTracker(int newline, int tabWidth, int line = 1, int column = 1)
    {
        _newline = newline;
        _tabWidth = tabWidth;
        _afterHighSurrogate = false;
        Line = line;
        Column = column;
    }

    public void Advance(string text, int start, int length)
    {
        int line = Line, column = Column;
        bool afterHigh = _afterHighSurrogate;
        for (int i = start, end = start + length; i < end; i++)
        {
            char c = text[i];
            if (c == _newline)
            {
                line++;
                column = 1;
                afterHigh = false;
            }
            else if (c == '\t')
            {
                column = ((column - 1) / _tabWidth + 1) * _tabWidth + 1;
                afterHigh = false;
            }
            else if (c < ' ')
            {
                afterHigh = false;   // other control characters take no width
            }
            else if (char.IsLowSurrogate(c) && afterHigh)
            {
                afterHigh = false;   // second half of a pair: already counted
            }
            else
            {
                column++;
                afterHigh = char.IsHighSurrogate(c);
            }
        }
        Line = line;
        Column = column;
        _afterHighSurrogate = afterHigh;
    }
}

// A growable window over a TextReader. Index 0 is the start of the current token.
// Chars are read on demand; Take() consumes from the front. The buffer only grows
// when a single token (plus its lookahead/overrun) doesn't fit.
internal sealed class LuthorCharWindow
{
    readonly TextReader _reader;
    char[] _buf;
    int _start, _end;
    bool _eof;

    public LuthorCharWindow(TextReader reader, int capacity = 4096)
    {
        _reader = reader ?? throw new ArgumentNullException(nameof(reader));
        _buf = new char[capacity];
    }

    /// <summary>Char at offset from the token start, or -1 at end of input.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int Peek(int offset)
        => _start + offset < _end ? _buf[_start + offset] : PeekSlow(offset);

    [MethodImpl(MethodImplOptions.NoInlining)]
    int PeekSlow(int offset)
    {
        while (_start + offset >= _end)
        {
            if (_eof) return -1;
            Fill();
        }
        return _buf[_start + offset];
    }

    void Fill()
    {
        if (_end == _buf.Length)
        {
            if (_start == 0)
            {
                Array.Resize(ref _buf, _buf.Length * 2);
            }
            else
            {
                int count = _end - _start;
                Array.Copy(_buf, _start, _buf, 0, count);   // overlap-safe
                _start = 0;
                _end = count;
            }
        }
        int n = _reader.Read(_buf, _end, _buf.Length - _end);
        if (n == 0) _eof = true;
        else _end += n;
    }

    public string Take(int length)
    {
        string s = new string(_buf, _start, length);
        _start += length;
        return s;
    }
}
static class JsonLexer
{
    private static int[] _dfa = {
        10, -1, -1, -1, 32, 0, 8, 101, 9, 10, 105, 11, 12, 101, 13, 13, 
        105, 14, 31, 101, 32, 32, 105, 33, 33, 101, 34, 34, 118, 35, 43, 101, 
        44, 44, 146, 45, 45, 150, 46, 47, 101, 48, 48, 160, 49, 57, 173, 58, 
        58, 189, 59, 90, 101, 91, 91, 193, 92, 92, 101, 93, 93, 197, 94, 101, 
        101, 102, 102, 201, 103, 109, 101, 110, 110, 208, 111, 115, 101, 116, 116, 215, 
        117, 122, 101, 123, 123, 222, 124, 124, 101, 125, 125, 226, 126, 55295, 101, 55296, 
        56319, 230, 56320, 65535, 101, 12, -1, -1, 0, 11, -1, -1, 3, 9, 10, 105, 
        13, 13, 105, 32, 32, 105, 12, -1, -1, 8, 0, 9, 237, 11, 33, 237, 
        34, 34, 265, 35, 91, 237, 92, 92, 269, 93, 55295, 237, 55296, 56319, 300, 57344, 
        65535, 237, 10, -1, -1, 0, 12, -1, -1, 2, 48, 48, 160, 49, 57, 173, 
        0, -1, -1, 3, 46, 46, 307, 69, 69, 314, 101, 101, 314, 0, -1, -1, 
        4, 46, 46, 307, 48, 57, 173, 69, 69, 314, 101, 101, 314, 9, -1, -1, 
        0, 5, -1, -1, 0, 6, -1, -1, 0, 12, -1, -1, 1, 97, 97, 327, 
        12, -1, -1, 1, 117, 117, 334, 12, -1, -1, 1, 114, 114, 341, 7, -1, 
        -1, 0, 8, -1, -1, 0, 12, -1, -1, 1, 56320, 57343, 101, -1, -1, -1, 
        8, 0, 9, 237, 11, 33, 237, 34, 34, 265, 35, 91, 237, 92, 92, 269, 
        93, 55295, 237, 55296, 56319, 300, 57344, 65535, 237, 1, -1, -1, 0, -1, -1, -1, 
        9, 34, 34, 237, 47, 47, 237, 92, 92, 237, 98, 98, 237, 102, 102, 237, 
        110, 110, 237, 114, 114, 237, 116, 116, 237, 117, 117, 348, -1, -1, -1, 1, 
        56320, 57343, 237, -1, -1, -1, 1, 48, 57, 361, -1, -1, -1, 3, 43, 43, 
        374, 45, 45, 374, 48, 57, 381, -1, -1, -1, 1, 108, 108, 388, -1, -1, 
        -1, 1, 108, 108, 395, -1, -1, -1, 1, 117, 117, 402, -1, -1, -1, 3, 
        48, 57, 409, 65, 70, 409, 97, 102, 409, 0, -1, -1, 3, 48, 57, 361, 
        69, 69, 314, 101, 101, 314, -1, -1, -1, 1, 48, 57, 381, 0, -1, -1, 
        1, 48, 57, 381, -1, -1, -1, 1, 115, 115, 422, -1, -1, -1, 1, 108, 
        108, 429, -1, -1, -1, 1, 101, 101, 433, -1, -1, -1, 3, 48, 57, 437, 
        65, 70, 437, 97, 102, 437, -1, -1, -1, 1, 101, 101, 450, 4, -1, -1, 
        0, 2, -1, -1, 0, -1, -1, -1, 3, 48, 57, 454, 65, 70, 454, 97, 
        102, 454, 3, -1, -1, 0, -1, -1, -1, 3, 48, 57, 237, 65, 70, 237, 
        97, 102, 237
    };
    public static IEnumerable<Parsley.Runtime.Token> Tokenize(TextReader reader, long position = 0, int line = 1, int column = 1, int tabWidth = 4) {
        foreach(var tok in LuthorRuntime.Tokenize(_dfa, reader, tabWidth, position, line, column))
        {
            if(tok.Symbol == whitespace) continue;
            yield return new Parsley.Runtime.Token(tok.Symbol, tok.Text, tok.Line, tok.Column, tok.Position);
        }
    }
    public static IEnumerable<Parsley.Runtime.Token> Tokenize(string text, long position = 0, int line = 1, int column = 1, int tabWidth = 4) {
        foreach(var tok in LuthorRuntime.Tokenize(_dfa, text, tabWidth, position, line, column))
        {
            if(tok.Symbol == whitespace) continue;
            yield return new Parsley.Runtime.Token(tok.Symbol, tok.Text, tok.Line, tok.Column, tok.Position);
        }
    }
    public const int number = 0;
    public const int @string = 1;
    public const int @true = 2;
    public const int @false = 3;
    public const int @null = 4;
    public const int lbracket = 5;
    public const int rbracket = 6;
    public const int lbrace = 7;
    public const int rbrace = 8;
    public const int colon = 9;
    public const int comma = 10;
    public const int whitespace = 11;
    public const int ERROR = 12;
}
