// <auto-generated>
// Synthesized by Parsley from Expr.xbnf. Changes are lost when it is synthesized again;
// add members in another part of this partial class instead.
// </auto-generated>
#nullable enable
using System.Collections.Generic;
using Parsley.Runtime;

/// <summary>
/// Parses Expr. Synthesized from Expr.xbnf.
/// </summary>
public partial class ExprParser : ParserBase
{
	#region Symbols
	public const int Expr = 0;
	public const int Term = 1;
	public const int Unary = 2;
	public const int Power = 3;
	public const int Primary = 4;
	public const int Number = 5;
	public const int Add = 6; // "+"
	public const int Sub = 7; // "-"
	public const int Mul = 8; // "*"
	public const int Div = 9; // "/"
	public const int Mod = 10; // "%"
	public const int Pow = 11; // "^"
	public const int Lparen = 12; // "("
	public const int Rparen = 13; // ")"
	public const int Whitespace = 14;
	public const int EndOfInput = 15;
	public const int ErrorSymbol = 16;
	public const int SymbolCount = 17;
	#endregion

	public ExprParser(IEnumerable<Token> tokens) : base(tokens, s_tables) { }

	/// <summary>
	/// Parses a complete Expr and returns its tree. Problems are reported in <see cref="ParserBase.Errors"/>.
	/// </summary>
	public static bool TryParse(IEnumerable<Token> tokens,out ParseNode result, out IReadOnlyList<ParseError> errors)
	{
		var parser = new ExprParser(tokens);
		result = parser.Run(parser.ParseExpr);
		errors = parser.Errors;
		return parser.Errors.Count == 0;
	}
	public static ParseNode Parse(IEnumerable<Token> tokens)
	{
		if(!TryParse(tokens, out var result, out var errors))
		{
			throw new ParseException(errors);
		}
		return result;
	}

	// Expr<start>= Term { add Term | sub Term }; (left recursion rewritten as a loop)
	ParseNode ParseExpr()
	{
		Enter(Expr);
		var node = NewNode(Expr);
		node.Add(ParseTerm());
		// { add Term | sub Term }
		while (Current.SymbolId is Add or Sub)
		{
			node = Fold(node);
			if (Current.SymbolId == Add)
			{
				Consume(node);
				node.Add(ParseTerm());
			}
			else
			{
				Expect(Sub, node);
				node.Add(ParseTerm());
			}
		}
		Leave();
		return node;
	}

	// Term= Unary { mul Unary | div Unary | mod Unary }; (left recursion rewritten as a loop)
	ParseNode ParseTerm()
	{
		Enter(Term);
		var node = NewNode(Term);
		node.Add(ParseUnary());
		// { mul Unary | div Unary | mod Unary }
		while (Current.SymbolId is Mul or Div or Mod)
		{
			node = Fold(node);
			switch (Current.SymbolId)
			{
				case Mul:
				case Div:
				case Mod:
					Consume(node);
					node.Add(ParseUnary());
					break;
				default:
					Error(node, null, Mul, Div, Mod);
					break;
			}
		}
		Leave();
		return node;
	}

	// Unary= sub Unary | Power;
	ParseNode ParseUnary()
	{
		Enter(Unary);
		var node = NewNode(Unary);
		if (Current.SymbolId == Sub)
		{
			Consume(node);
			node.Add(ParseUnary());
		}
		else
		{
			node.Add(ParsePower());
		}
		Leave();
		return node;
	}

	// Power= Primary [ pow Unary ];
	ParseNode ParsePower()
	{
		Enter(Power);
		var node = NewNode(Power);
		ParsePrimary(node);
		// [ pow Unary ]
		if (Current.SymbolId == Pow)
		{
			Consume(node);
			node.Add(ParseUnary());
		}
		Leave();
		return node;
	}

	// Primary<collapsed>= number | lparen Expr rparen;
	void ParsePrimary(ParseNode parent)
	{
		Enter(Primary);
		if (Current.SymbolId == Number)
		{
			Consume(parent);
		}
		else
		{
			Expect(Lparen, parent);
			parent.Add(ParseExpr());
			Expect(Rparen, parent);
		}
		Leave();
	}

	#region Tables
	static readonly ParserTables s_tables = new(
		terminalStart: Number, // lexer ids count terminals from 0; the parser adds this
		symbolNames: ["Expr", "Term", "Unary", "Power", "Primary", "number", "add", "sub", "mul", "div", "mod", "pow", "lparen", "rparen", "whitespace", "#EOS", "#ERROR"],
		displayNames: ["Expr", "Term", "Unary", "Power", "Primary", "number", "\"+\"", "\"-\"", "\"*\"", "\"/\"", "\"%\"", "\"^\"", "\"(\"", "\")\"", "whitespace", "end of input", "an unrecognized token"],
		collapsedTerminals: [Lparen, Rparen],
		// for each non-terminal, where error recovery can stop while parsing it: what can follow it, plus its sync terminals
		recoverySets:
		[
			[Rparen, EndOfInput], // Expr
			[Add, Sub, Rparen, EndOfInput], // Term
			[Add, Sub, Mul, Div, Mod, Rparen, EndOfInput], // Unary
			[Add, Sub, Mul, Div, Mod, Rparen, EndOfInput], // Power
			[Add, Sub, Mul, Div, Mod, Pow, Rparen, EndOfInput] // Primary
		],
		syncTerminals: [],
		endOfInput: EndOfInput,
		error: ErrorSymbol);
	#endregion
}
